source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'pills' do
    use_frameworks!
    pod 'Alamofire', '~> 4.9.1'
    pod 'AlamofireImage', '~> 3.6.0'
    pod 'Anchorage', '~> 4.3.1'
    pod 'FSPagerView', '~> 0.8.0'
end
